### ISSUE TITLE
Intervals with duration 0

### ISSUE THREAD

**Issue by christianbrodbeck** [kylebgorman/textgrid#15]
I just ran into some weird behavior in Praat when editing an interval tier and think I traced it back to an interval with duration 0 (at the place where no boundary is displayed in the screenshot); would it make sense to disallow Intervals with duration 0? Could be done by modifying the check at https://github.com/kylebgorman/textgrid/blob/master/textgrid/textgrid.py#L173.

![screen shot 2016-12-29 at 2 00 10 pm](https://cloud.githubusercontent.com/assets/145771/21544439/25d0ba1a-cdcf-11e6-9230-45fa98d9c34f.png)

**Comment by kylebgorman** [comment]
It's not clear to me from that picture what the problem is. Is it that you
expect a vertical blue line at the right side of the yellow interval?

If this is just a Praat *rendering* bug, but Praat is okay with
zero-duration intervals, I'd be inclined to leave it as is. That is,
there's nothing illformed about the TextGrid, it's just that Praat (some
versions, on some platforms) misrenders it.

If however this is a reflection of the fact that Praat (sorta) disallows
zero-duration intervals, then I'd be glad to accept a patch at that point.

Can we determine which it is?

**Comment by christianbrodbeck** [comment]
>  Is it that you expect a vertical blue line at the right side of the yellow interval?

Yes, also:

- The invisible boundary can't be moved.
- if I add a new boundary in the area after the invisible boundary and save the textgrid, the resulting TextGrid file can not be opened by Praat anymore, giving the error below.

These suggest to me that this is something that is not intended to happen...

![screen shot 2016-12-29 at 11 11 12 pm](https://cloud.githubusercontent.com/assets/145771/21555845/1c835d12-ce1c-11e6-922e-dec0de5c1d37.png)

**Comment by kylebgorman** [comment]
Okay, I find that convincing, let's rule it out. Are you up to creating a
PR that prevents creation of such a tier (presumably by raising an
exception)?

**Comment by christianbrodbeck** [comment]
Yes I will create a PR, thanks!
