### ISSUE TITLE
How does one use this?

### ISSUE THREAD

**Issue by darksipu** [kylebgorman/textgrid#26]
Hi, 

Thanks a lot for coding this. I'm just a bit confused on how to use it. I've how a .mlf file from HTK that I need to get into TextGrid format.

Do I need to import textgrid into Python and then call some functions on it?

Or is there a command line that I can use? python textgrid.py filename.mlf ??

Some documentation would help.

Cheers

**Comment by kylebgorman** [comment]
There is no command-line tool since it's not obvious what it would do. (For instance in your hypothetical example of processing an MLF file does that create textgrid files...if so where, and what are they called?)

However a good place to start ot read about this is to look at the tests in `tests.py`. They show the module in use (yes you have to import it.) and cover most of its functionality.

If you find this insufficient (but are able to understand what's happening there) we welcome pull requests to improve the documentation. The current presumption here is that, because this is a middleware module rather than a command-line tool, you know enough to interpret Python function signatures to get this working.
